### ISSUE TITLE
Colour of socketed gems ignored

### ISSUE THREAD

**Issue by eps1lon** [PoE-Profile/poe-profile#15]
Example profile: http://poe-profile.info/profile/eps1lon/epsilonSpitsFyah

The portal gem socketed into the body armour is displayed as red. 

https://github.com/PoE-Profile/poe-profile/blob/4a2cd90f776cf250a83b0dfe24fb7b53256cc7e5/resources/assets/js/components/profile/Socket.vue#L48-L57

This should be abstracted so that it always generates a css class that contains socket **and** gem colour and the css stylesheet should handle the combinations.

**Comment by IvanD87** [comment]
We didn't have images for white skill gems and forgot after that.
Should be fixed now.
