### ISSUE TITLE
Profile Load Error

### ISSUE THREAD

**Issue by slushi** [PoE-Profile/poe-profile#8]
Looks like there is a JS error on loading a profile:

![screen shot 2018-03-05 at 2 00 43 pm](https://user-images.githubusercontent.com/10413330/36996953-b75e4e14-207d-11e8-842d-443ac69d480c.png)

Browser: Chrome (Version 64.0.3282.186)

**Comment by kas7err** [comment]
We did not have cache-busting, try with ctrl+f5 or clearing cache manually.This is gonna be fixed in our next update in a few days.

**Comment by slushi** [comment]
Yup that was it! Great work team!
